/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package morrow;

import morrow.servlet.MorrowServlet;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletHandler;
import org.junit.jupiter.api.Test;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MorrowServletTest {
    @Test
    void startServlet() throws Exception {
        Server server = new Server(8080);
        ServletHandler servletHandler = new ServletHandler();
        servletHandler.addServletWithMapping(MorrowServlet.class, "");
        server.setHandler(servletHandler);
        server.start();

        HttpClient client = HttpClient.newHttpClient();
        var request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:8080"))
                .header("Accept", "application/json")
                .GET()
                .build();
        HttpResponse<String> httpResponse = client.send(request, HttpResponse.BodyHandlers.ofString());
        assertEquals("{\"status\": \"ok\"}", httpResponse.body());


    }
}
